### ISSUE TITLE
How can i get cropped image as base64 encoded data ? 

### ISSUE THREAD

**Issue by webstar1987923** [danielthall/ember-cropperjs#12]

**Comment by ynotdraw** [comment]
hi @webstar1987923, you should just need to grab the cropped canvas as a blob and then be able to encode it however you'd like.  If you want to encode it as the cropper moves around, you can do something like below. 

If you have a template like:

```hbs
{{#image-cropper
  source=photo
  options=(hash ...your options here)
as |cropper|}}

  {{cropper.on 'crop' action=(action 'cropImage')}}
{{/image-cropper}}

```

and in your controller/component:
```js
_updateFileBlob(cropper) {
  const yourBlob = cropper.getCroppedCanvas(/* any options you want */).toBlob();
 // encode the data however you'd like after this
},

actions: {
    cropImage(cropper) {
      debounce(this, this._updateFileBlob, cropper, 100);
    }
}
```

**Comment by rinoldsimon** [comment]
To get a cropped image as base64 encoded data use, `cropper.getCroppedCanvas().toDataURL()`

**Comment by ynotdraw** [comment]
@webstar1987923 hope @rinoldsimon and I provided a few options for you! Going to go ahead and close this issue.  Please feel free to reopen if this doesn't take care of you!
