### ISSUE TITLE
issue with cropper source

### ISSUE THREAD

**Issue by rinoldsimon** [danielthall/ember-cropperjs#14]
when i upload a different image and update the {{#cropper-image `source=*thelatestuploadedimageurl*` ... }}. the source changes but the previous options are not getting set to the new image.

**Comment by ynotdraw** [comment]
@rinoldsimon could you send me what options you are setting prior to changing the source?  There may be some we are missing.  There are some properties where we tear down and construct a new Cropper instance completely, so some of those options may be getting lost if we aren't copying things over properly.

**Comment by rinoldsimon** [comment]
**hbs**
```
{{#image-cropper
  source=model.profile_photo
  options=(hash
    aspectRatio=1
    viewMode=2
    minContainerWidth=748
    minContainerHeight=400
    ...
    ...
  )  as |cropper|}}
{{/image-cropper}}
```
I'm using `ember-file-upload` addon for `file uploads`
So when i select a image file from my local machine `uploadPhoto` action will be called where i set `source` to the new image.
**js**
```
uploadPhoto(file) {
  file.readAsDataURL().then((url) => {
    set(model, 'profile_photo', url);
    ...
    ...
  }
```
In this scenario `cropper` `source` is changed to the new image. But the previous `cropper` `options` are not available. So i get a different view with different `minContainerWidth`, `minContainerHeight`, etc..

According the `cropperjs` document there is a method `replace(url)`
How to call the method in `uploadPhoto` action ?

**Comment by ynotdraw** [comment]
Right, we are calling `replace` already here when the source changes: https://github.com/danielthall/ember-cropperjs/blob/master/addon/components/image-cropper.js#L91

I wonder if we're just missing passing additional options after a replace or something.  I can dig in a bit more later this evening.

**Comment by rinoldsimon** [comment]
`hasSameSize` param to `true` 
`_cropper.replace(source, true)` works.
According to the `cropperjs` doc, It will not rebuilt the cropper and only update the urls of all related images

**Comment by rinoldsimon** [comment]
is the addon uses the latest verions of `cropper js` ?

**Comment by ynotdraw** [comment]
Thanks for digging in more, @rinoldsimon.  Could you try using the branch at https://github.com/danielthall/ember-cropperjs/tree/replace-hasSameSize-fix and let me know if this resolves the issue for you?

I have an open issue for upgrading to the latest version of `cropperjs`.  It looks like `replace` with the  sameSize option is supported in the version we are using though.  If this doesn't work, I'll upgrade to the latest version of cropperjs and try again.

**Comment by rinoldsimon** [comment]
I forgot to add this rule.
```
img {
  max-width: 100%;
}
```
adding the above rule fixes the issue
