### ISSUE TITLE
Changing "zoomable" after first initialization doesn't take effect

### ISSUE THREAD

**Issue by xtagon** [danielthall/ember-cropperjs#33]
Hi,

I have a use case where I need to toggle "zoomable" from a checkbox control. The problem I'm seeing is that this change doesn't take effect. The default value of that option takes effect, whether I make it `true` or `false, but it can't change that value after the fact.

I noticed in the code there is a short list of options that require complete re-instantiation of the cropper. Is this one of those options, and if so, would adding `zoomable` to that list fix this?

https://github.com/danielthall/ember-cropperjs/blob/master/addon/components/image-cropper.js#L15

Thanks!

**Comment by ynotdraw** [comment]
Hey @xtagon,

Have you tried passing it into the `options` hash?

```
{{#image-cropper
  source='sinbad2_800x600.jpg'
  options=(hash
    zoomable=yourZoomableVar
  ) as |cropper|}}

{{/image-cropper}}
```

If that still isn't doing the trick, then yeah, the re-instantiation route is probably best. I'd be surprised if that took a re-instantiation though, but maybe so! Totally open to PRs as well if you get it working!

**Comment by xtagon** [comment]
Yeah, passing it into the `options` hash was what I tried. It worked on the first load, but it didn't change when `youZoomableVar` changed.

Does it work for you? Maybe I'm doing something differently?

**Comment by xtagon** [comment]
Adding `zoomable` to the list of options that require re-instantiation does work (it enables zoom after re-instantiating) but the problem is that re-instantiating causes the current crop data to be reset and lost.

Any suggestions for how to get around this?

**Comment by xtagon** [comment]
It doesn't seem to retain the image source either, but I'm still trying to determine if that's a problem with my application or the cropper library.

**Comment by xtagon** [comment]
After a few iterations I was able to solve the parts that weren't working correctly. Please give me a heads up when you've had a chance to review the PR as I'd like to decide whether or not to use a fork in the mean time.

Thank you so much, this library has been fantastic by the way :)
