### ISSUE TITLE
Add a tag for version `0.8.0`

### ISSUE THREAD

**Issue by tniezurawski** [danielthall/ember-cropperjs#36]
From what I see version `0.8.0` was released at the end of April 2019.

Please add a tag and release note as they are missing now:
![image](https://user-images.githubusercontent.com/4335166/63266836-18956080-c291-11e9-813b-81a0463112ea.png)

A small Changelog with:
```
### 0.8.0
* Ember Fastboot support added
```
would be a nice addition :)

**Comment by ynotdraw** [comment]
@tniezurawski v0.8.0 has been released as well as v0.9.0
