### ISSUE TITLE
Issues with re-initializing cropper on attributes change

### ISSUE THREAD

**Issue by xtagon** [danielthall/ember-cropperjs#4]
After testing https://github.com/danielthall/ember-cropperjs/pull/1 in a real app scenario, it's not quite working right for me. A couple issues:

1. Now it will re-initialize the cropper instance on any attribute change, so even if I just change the aspect ratio for instance, it will re-initialize the entire cropper.

2. It shouldn't have to re-initialize the entire cropper anyway. When the source attribute changes, there is a `cropper.replace()` function that can be called.

I am working around these issues in my app by reverting to 0.1.0 and using something like this in my parent component:

```
  updateSource: observer("cropper", "source", function() {
    const cropper = this.get("cropper");
    if (cropper) {
      cropper.replace(this.get("source"));
    }
  }),

  updateAspectRatio: observer("aspectRatio", "cropper", function() {
    const aspectRatioValue = this.get("aspectRatioValue");
    const cropper = this.get("cropper");

    if (aspectRatioValue && cropper) {
      cropper.setAspectRatio(aspectRatioValue);
    }
  }),
```

I'd love to do a PR to help fix this. But are observers the recommended way to do this, or is there a better way? If I remember correctly, didReceiveAttrs doesn't actually tell you which attribute has changed, does it?

**Comment by ynotdraw** [comment]
Yeah, this is an interesting problem. It'd be best if we didn't have to use observers and/or know which properties we need to watch explicitly. I'll dig around some more to see if we can come up with something that'll fit most use cases. Do you happen to have a link or some examples in how you are using this addon? Sounds like you are updating the `aspectRatio` dynamically?

**Comment by xtagon** [comment]
I don't have a link because the code base I'm working with is not open source. However I will help in any way I can.

Right now I'm using a custom component and template that renders a few controls as well as rendering the cropper component. The parent component has controls for changing the aspect ratio (in the form of a few preset Ember objects that compute down to the percentage-based value that cropper.js expects). The parent component also controls which image is loaded at any given time so you can switch between them.

So, it currently has observers (in the parent component) that dynamically set the aspect ratio and change the source on the cropper as it is updated. I know this is not the best way, but I'm unsure what is.

The parent gets its reference to the cropper component in a strange way as well, by registering on the "ready" event and storing it as a property.

In fact, I'm not even sure that my cropper.js component isn't reloading completely anyway, because if the selected photo changes in the parent component, the template might re-render the cropper component completely.

For what it's worth, I tried a couple other cropper.js wrappers before this one, and yours is the only one I've made significant progress on. Big thanks to you for writing it 👍 

How do other wrapper libraries handle the issue of dynamically updating properties?

**Comment by ynotdraw** [comment]
Hello! Apologies on the delayed response.  Yeah, I think what we need to do for the component is know a bit more about which properties can be updated directly on the `cropper` instance via a set method (for example, `setAspectRatio` and `replace` as you mentioned here).  Then, as you mentioned, instead of tearing down the cropper instance and creating a new one, on a property change, the component would know what to do.

I need to take a closer look at the docs when I get a chance to determine when a completely new Cropper instance is required, or if everything can be updated via a method exposed on the Cropper instance.  I think all of this can be taken care of by doing something like below.

```javascript
import Ember from 'ember';
import layout from '../templates/components/image-cropper';
import Cropper from 'cropperjs'
import { copy } from '@ember/object/internals'
import { scheduleOnce } from '@ember/runloop';
import { compare } from '@ember/utils';

const {
  Component,
  copy,
  get,
  run,
  set
} = Ember;

// Properties that require a completely new Cropper instance
const OPTS_REQUIRE_NEW = [
  'image'
];

// Properties that do not require a new instance, rather just need to call
// a method on the existing Cropper instance
const OPT_UPDATE_METHODS = {
  'aspectRatio': 'setAspectRatio'
};

export default Component.extend({
  classNames: [ 'image-cropper' ],
  layout,

  options: null,

  _cropper: null,
  _prevOptions: null,

  didInsertElement() {
    this._super(...arguments);

    scheduleOnce('afterRender', this, this._setup);
  },

  didUpdateAttrs() {
    this._super(...arguments);

    if (this._cropper === null) {
      return;
    }

    const options = get(this, 'options');

    if (OPTS_REQUIRE_NEW.any((opt) => compare(options[opt], this._preOptions[opt]) !== 0) {
      this._cropper.destroy();

      this._prevOptions = copy(options);

      this._cropper = new Cropper(document.getElementById(`image-cropper-${get(this, 'elementId')}`), this._prevOptions);
      this.notifyPropertyChanged('_cropper');
      return;
    }

    for (const opt of OPT_UPDATE_METHODS) {
      if (compare(options[opt], this._preOptions[opt]) !== 0) {
        this._cropper[OPT_UPDATE_METHODS[opt]](options[opt]);
      }
    }

    this._prevOptions = copy(options);
  },

  willDestroyElement() {
    this._super(...arguments);

    if (this._cropper !== null) {
      this._cropper.destroy();
    }
  },

  _setup() {
    this._prevOptions = copy(get(this, 'options'));

    this._cropper = new Cropper(document.getElementById(`image-cropper-${get(this, 'elementId')}`), this._prevOptions);
    this.notifyPropertyChanged('_cropper');
  }
});
```

I can get to these changes hopefully in the next week or two, but you have some extra bandwidth to work on this, just let me know!

**Comment by xtagon** [comment]
Sounds great to me! Let me know how I can help.

The workarounds are doing okay for now, so I'd love to help do this the "right way" instead of rushing it 👍 

I'm not sure what other methods would map to option bindings but with the code you posted above, it seems like they would be easy to tack on as we find them

**Comment by ynotdraw** [comment]
@xtagon awesome! I may have a branch for you to try out here soon. I'm wrapping a few things up now.  When ready, it'd be awesome if you could run your app against the branch I'll provide and ensure it works as you expect!

**Comment by xtagon** [comment]
That sounds great and I'll be glad to test the branch :)

**Comment by ynotdraw** [comment]
@xtagon give this branch a whirl whenever you have time and let me know how things go! I'll need to write some tests and implement the other supported options, but this should hopefully cover the example you provided above!

https://github.com/danielthall/ember-cropperjs/tree/update-options-refactor

**Comment by xtagon** [comment]
I'm excited to try it but it's looking like I won't have time this week. I'll set myself a reminder and follow up when I can :)

Thanks for the help!

**Comment by ynotdraw** [comment]
@xtagon No worries!

**Comment by xtagon** [comment]
Hi @ynotdraw - your changes worked great and I was able to remove the observers. Thanks! Looking forward to a release.

👍

**Comment by ynotdraw** [comment]
Good to hear @xtagon, thanks for testing with your app! I hope to have some time this weekend to get this across the finish line - I'll follow up here when the new version is released. Thanks!

**Comment by xtagon** [comment]
Thank you :-)

**Comment by ynotdraw** [comment]
@xtagon sorry, I totally dropped the ball on this.  I just need to test with one of our applications and make sure everything is good to go. After that, just need to release it.  I'll try to get to it this week/weekend.

**Comment by xtagon** [comment]
Awesome 👍

**Comment by ynotdraw** [comment]
@xtagon ember-cropperjs@0.3.0 has been released.  Let me know if you hit any issues!

**Comment by xtagon** [comment]
@ynotdraw Thanks so much! 👍

**Comment by ynotdraw** [comment]
@xtagon no problem!
